export const IntegrationSource = {
  THF: 'THF',
  AYHL: 'AYHL',
  GAMESHEET: 'GAMESHEET',
}

export const MatchStatus = {
  LINKED: 'LINKED',
  AMBIGUOUS_SELECTION_REQUIRED: 'AMBIGUOUS_SELECTION_REQUIRED',
  NO_MATCH: 'NO_MATCH',
}

export const LinkState = {
  PENDING_SELECTION: 'PENDING_SELECTION',
  CONFIRMED: 'CONFIRMED',
  REVERIFY_REQUIRED: 'REVERIFY_REQUIRED',
  UNLINKED: 'UNLINKED',
}
