"""
Phase 2: Scrape rosters from Atlantic Hockey (atlantichockey.org).

This script:
1. Accepts a season year (e.g. `--season 2025` for 2025-2026 season)
2. Reads the discovered league-team list from CSV (e.g., 2025-ayhl-teams.csv)
3. For each team, scrapes the roster data
4. Saves roster data to CSV (e.g., 2025-ayhl-rosters.csv)

The input CSV should be generated by discover_teams.py first.

Usage:
  python discover_teams.py --season 2025
  python scrape_rosters.py --season 2025
"""

import argparse
import csv
import time
import re
import os
from playwright.sync_api import sync_playwright


def parse_roster_table(table):
    """Parse a Playwright table element into header and row texts."""
    rows = table.query_selector_all('tbody tr')
    parsed = []
    header = []
    if not rows:
        return header, parsed

    first_cols = rows[0].query_selector_all('td')
    first_texts = [c.inner_text().strip() for c in first_cols] if first_cols else []
    is_header = any('PLAYER' in t.upper() or 'BD' in t.upper() or 'BIRTH' in t.upper() for t in first_texts)
    start_idx = 0
    if is_header:
        header = first_texts
        start_idx = 1

    for r in rows[start_idx:]:
        cols = r.query_selector_all('td')
        texts = [c.inner_text().strip() for c in cols]
        if texts:
            parsed.append(texts)

    return header, parsed


def scrape_roster_page(page, url):
    """Load a single roster URL and return parsed roster dict or None."""
    try:
        page.goto(url, timeout=15000)
    except Exception:
        return None

    team_name = None
    header_el = page.query_selector('div.pageHeader')
    if header_el:
        team_name = header_el.inner_text().strip()

    # Extract season/league visible text with '::'
    season = None
    league = None
    body = page.query_selector('body')
    visible_text = body.inner_text() if body else ''
    for line in visible_text.split('\n'):
        if '::' in line:
            parts = line.split('::')
            if len(parts) == 2:
                season = parts[0].strip()
                league = parts[1].strip()
                break

    # Find roster table
    tables = page.query_selector_all('table')
    for t in tables:
        header, rows = parse_roster_table(t)
        if rows:
            hdr_upper = [h.upper() for h in header]
            if header and (any('PLAYER' in h for h in hdr_upper) or any('BD' in h or 'BIRTH' in h for h in hdr_upper)):
                player_dicts = []
                for texts in rows:
                    d = {}
                    if header and len(header) <= len(texts):
                        for i, col_name in enumerate(header):
                            key = col_name.strip().lower()
                            d[key] = texts[i] if i < len(texts) else ''
                    else:
                        d['number'] = texts[0] if len(texts) > 0 else ''
                        d['player'] = texts[1] if len(texts) > 1 else ''
                        d['pos'] = texts[2] if len(texts) > 2 else ''
                        d['ht'] = texts[3] if len(texts) > 3 else ''
                        d['wt'] = texts[4] if len(texts) > 4 else ''
                        d['shot'] = texts[5] if len(texts) > 5 else ''
                        d['bd'] = texts[6] if len(texts) > 6 else ''
                        d['hometown'] = texts[7] if len(texts) > 7 else ''
                    player_dicts.append(d)

                return {
                    'team_name': team_name,
                    'season': season,
                    'league': league,
                    'players': player_dicts,
                    'header': header,
                }

    return None


def main():
    parser = argparse.ArgumentParser(description="Scrape rosters from Atlantic Hockey using a discovered teams CSV file.")
    parser.add_argument('input_file', help='Input CSV file with discovered teams (e.g., "2025-ayhl-teams.csv")')
    parser.add_argument('--output', help='Output CSV file for rosters (default: auto-generated from input file name)')
    parser.add_argument('--delay', type=float, default=0.1, help='Delay between requests (seconds)')
    args = parser.parse_args()

    input_file = args.input_file

    # Infer season from filename to provide helpful messages
    season_year_from_filename = None
    match = re.search(r'(\d{4})', os.path.basename(input_file))
    if match:
        season_year_from_filename = int(match.group(1))

    # Determine output file
    output_file = args.output
    if not output_file:
        # Generate from input: 2025-ayhl-teams.csv -> 2025-ayhl-rosters.csv
        output_file = input_file.replace('teams.csv', 'rosters.csv')
        # As a fallback, if 'teams.csv' isn't in the name
        if output_file == input_file:
            base, ext = os.path.splitext(input_file)
            output_file = f"{base}-rosters.csv"


    # Read the discovered teams list
    print(f"\n{'='*70}")
    print(f"PHASE 2: SCRAPE ROSTERS")
    print(f"{'='*70}\n")

    print(f"Reading discovered teams from '{input_file}'...")
    
    league_team_list = []
    try:
        with open(input_file, 'r', encoding='utf-8') as csvfile:
            reader = csv.DictReader(csvfile)
            league_team_list = list(reader)
    except FileNotFoundError:
        print(f"❌ Error: File '{input_file}' not found.")
        if season_year_from_filename:
            print(f"   Please run 'python discover_teams.py --season {season_year_from_filename}' first")
        else:
            print(f"   Please ensure the input file exists.")
        return
    
    if not league_team_list:
        print("No teams found in input file. Exiting.")
        return
    
    print(f"✅ Loaded {len(league_team_list)} league-team pairs\n")
    
    fieldnames = ['season_year', 'seasonid', 'leagueid', 'teamid', 'team', 'number', 'player', 'pos', 'ht', 'wt', 'shot', 'birthdate', 'hometown']

    print(f"Scraping rosters for {len(league_team_list)} teams...")
    print(f"Output: '{output_file}'\n")

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()

        with open(output_file, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()

            total_found = 0
            for idx, item in enumerate(league_team_list, 1):
                league_name = item['league_name']
                team_name = item['team_name']
                team_params = item['team_params']
                leagueid = int(item['leagueid'])
                seasonid = int(item['seasonid'])
                season_year = int(item['season_year'])
                
                url = f"https://atlantichockey.org/teamroster.php{team_params}"
                
                try:
                    res = scrape_roster_page(page, url)
                except Exception as e:
                    res = None
                
                # Extract teamid from team params
                teamid = None
                if team_params.startswith('?'):
                    params_str = team_params[1:]
                    for param in params_str.split('&'):
                        if param.startswith('teamid='):
                            teamid = int(param.split('=')[1])
                            break
                
                if res and res.get('players'):
                    roster_team_name = res.get('team_name') or team_name or ''
                    
                    for pd in res['players']:
                        row = {
                            'season_year': season_year,
                            'seasonid': seasonid,
                            'leagueid': leagueid,
                            'teamid': teamid or '',
                            'team': roster_team_name,
                            'number': pd.get('#') or pd.get('number') or '',
                            'player': pd.get('player') or pd.get('player name') or pd.get('player_name') or '',
                            'pos': pd.get('pos') or pd.get('position') or '',
                            'ht': pd.get('ht') or '',
                            'wt': pd.get('wt') or '',
                            'shot': pd.get('sh') or pd.get('shot') or '',
                            'birthdate': pd.get('bd') or pd.get('birthdate') or '',
                            'hometown': pd.get('hometown') or '',
                        }
                        writer.writerow(row)
                        total_found += 1
                    
                    print(f"  [{idx:3d}/{len(league_team_list)}] ✅ {league_name:20s} → {team_name:25s}: {len(res['players']):2d} players")
                else:
                    print(f"  [{idx:3d}/{len(league_team_list)}] ⏭️  {league_name:20s} → {team_name:25s}: no roster found")
                
                # Polite delay
                time.sleep(args.delay)

        print(f"\n✅ DONE. Total player rows written: {total_found} to '{output_file}'")
        browser.close()


if __name__ == '__main__':
    main()
